### ISSUE TITLE
Could you provide a detailed instruction

### ISSUE THREAD

**Issue by StevenTang1998** [Ravoxsg/SummaReranker#1]
Hello, congratulations on your work being accepted for ACL 2022!

I want to follow your work and reproduce the results. However, the script you provide didn't run successfully in my environment. There seems to be some local paths, and the location and format of the dataset are not particularly clear.

Could you offer some help and wish you a happy life!

**Comment by Ravoxsg** [comment]
Hi @StevenTang1998 , thanks!

So in order to run the re-ranker, you need to first generate a set of summary candidates
This is done in src/candidate_generation/main_candidate_generation.py
This will generate num_beams candidate for each source document in the dataset.

Then, you need to score these candidates to evaluate the re-ranking.
This is done in src/candidate_generation/main_scores.py

Let me know if you need any help running these scripts.

**Comment by Ravoxsg** [comment]
@StevenTang1998  Please follow instructions from the other similar issue:
https://github.com/Ravoxsg/SummaReranker/issues/2
