### ISSUE TITLE
Generation Hyperparameters

### ISSUE THREAD

**Issue by Hannibal046** [Ravoxsg/SummaReranker#5]
Hi, thanks for your great work. I am wondering how to get these generation hyperparameters ? 
https://github.com/Ravoxsg/SummaReranker/blob/16337a965104a48e39309c26c81a47b9304a16d8/src/candidate_generation/main_candidate_generation.py#L78-L84

**Comment by Ravoxsg** [comment]
@Hannibal046  Do you mean how I obtained them? 
I followed hyper-parameters shared by the PEGASUS paper. Otherwise, when not available, I used the Huggingface fine-tuned PEGASUS and BART checkpoints and varied hyper-parameters to be as close as possible to the numbers reported by the PEGASUS and BART papers. For instance for the PEGASUS checkpoint on CNN/DM, the ROUGE-1/2/L I got with these hyper-parameters are within 0.1% of what's reported by the PEGASUS paper.

**Comment by Hannibal046** [comment]
Got it. Thanks !
